#!/usr/bin/env bash

# cd to the directory of this script
project_root=$(dirname "$0")
project_root=$(readlink -f $project_root) # make sure . gets expanded
cd $project_root

size_file=host_size.txt
touch ./$size_file
chmod +r ./$size_file

while [[ true ]]; do
  echo "# this file is auto-generated by the shared-tmux systemd service" \
    > ./$size_file
  echo "lines `tput lines`" >> ./$size_file
  echo "columns `tput cols`" >> ./$size_file
  sleep 1
done
